Update build_linux.yml

diff --git a/.github/workflows/build_linux.yml b/.github/workflows/build_linux.yml
--- a/.github/workflows/build_linux.yml
+++ b/.github/workflows/build_linux.yml
@@ -59,8 +59,8 @@ jobs:
       env:
         QT_DEBUG_PLUGINS: 1
       run: |
-        export QT_PLUGIN_PATH=$(uv python -c "import PySide6; import os; print(os.path.join(PySide6.__path__[0], 'Qt', 'plugins'))")
-        xvfb-run --auto-servernum uv python scripts/build_linux.py > build_log.txt 2>&1 || (echo "Build Failed! Check local environment." && exit 1)
+        export QT_PLUGIN_PATH=$(uv run python -c "import PySide6; import os; print(os.path.join(PySide6.__path__[0], 'Qt', 'plugins'))")
+        xvfb-run --auto-servernum uv run python scripts/build_linux.py > build_log.txt 2>&1 || (echo "Build Failed! Check local environment." && exit 1)
 
     - name: Rename AppImage
       # 使用 Secret 重新命名打好的 AppImage 包，隐藏原始的中文或特殊包名
